stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - bash ./build.sh
    - echo "Compile complete."
  tags:
    - docker

deploy-job:
  stage: deploy
  script:
    - echo "Deploying applicartion..."
    - bash ./deploy.sh
    - echo "Application Successfully deployed."
  tags:
    - docker