stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - bash ./build.sh
    - echo "Compile complete."
  cache:
    key: "$CI_COMMIT_BRANCH"
    paths:
      - node_modules/
  tags:
    - shared

deploy-release-job:
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
  stage: deploy
  script:
    - echo "Deploying application..."
    - bash ./deploy-release.sh
    - echo "Application Successfully deployed."
  tags:
    - shared

deploy-debug-job:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  stage: deploy
  script:
    - echo "Deploying Test Application..."
    - bash ./deploy-debug.sh
    - echo "Application Successfully deployed."

